# Project information
site_name: Вообще любой рандомный сайт какой вы захотите
site_url: https://Septemberer.github.io/devops-lab-laptev/
site_author: Автор Сайта (ex Лаптев Анатолий)
site_description: >-
  Тут описание вашего сверх сайта

# Repository
repo_name: Septemberer/devops-lab-laptev
repo_url: https://github.com/Septemberer/devops-lab-laptev

# Copyright
copyright: Copyright &copy; 2020 - 2025 Anatoly Laptev

# Theme
theme:
  name: material
  language: ru
  features:
    - navigation.tabs
    - navigation.sections
    - navigation.top
    - search.highlight
    - search.share
    - toc.follow
  palette:
    - scheme: default
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-night
        name: Включить тёмную тему
    - scheme: slate
      primary: indigo
      accent: indigo
      toggle:
        icon: material/weather-sunny
        name: Включить светлую тему

# Plugins
plugins:
  - search

nav:
  - Домой:
    - Начало: index.md
    - Источник стресса: my_car.md
    - Позитивные аспекты: positive_corner.md
    - Негативные аспекты: negative_corner.md
  - Секретная вкладка: secret.md

# Иконки соцсетей в футере (опционально)
extra:
  social:
    - icon: fontawesome/brands/github
      link: https://github.com/Septemberer

# Расширения Markdown (красивые блоки, таблицы, заметки)
markdown_extensions:
  - admonition
  - attr_list
  - footnotes
  - toc:
      permalink: true
  - pymdownx.betterem:
      smart_enable: all
  - pymdownx.details
  - pymdownx.emoji:
      emoji_generator: !!python/name:material.extensions.emoji.to_svg
      emoji_index: !!python/name:material.extensions.emoji.twemoji
  - pymdownx.highlight:
      anchor_linenums: true
  - pymdownx.keys
  - pymdownx.tabbed:
      alternate_style: true